services:
  zap1:
    build:
      context: .
    container_name: zap1
    env_file: .env.mainnet
    volumes:
      - ./data:/data
      # Uncomment when anchor automation is activated:
    network_mode: host
    restart: unless-stopped
